Fixed issue #37
When trying to compile on newer linux distros the following errors occured:
```
  File "/home/mmxgn/git/libaudioverse/bindings/transformers.py", line 55, in common_prefix
    return os.path.commonprefix(l)
TypeError: 'odict_keys' object does not support indexing
```
This was because line 34 at `bindings/libadioverse/__init__.py` passed `constants.keys()` to
`os.path.common_prefix` which tried to index it using an integer which is not allowed any more